### ISSUE TITLE
自定义颜色只有在更改了颜色的选择后才会被应用

### ISSUE THREAD

**Issue by FiveYellowMice** [tcdw/minecraft-text-editor#1]
~由于 Firefox 的自选颜色工具是在独立的窗口中，因此在点击自定义颜色的按钮后，文本框的选中状态会被丢失，从而导致在选定颜色后，文本框中的文字没有得到修改。~

~大概需要保存一下选中状态什么的。~

参见：  https://github.com/tcdw/minecraft-text-editor/issues/1#issuecomment-706538032

**Comment by tcdw** [comment]
FireFox 的颜色选择器我的确测试过，但只是在 Windows 和 macOS。。
不过我会看看如何加个 workaround

**Comment by FiveYellowMice** [comment]
唔，这边在 Windows 的 Firefox 上面也尝试了一下，也是有同样的问题呢。

**Comment by tcdw** [comment]
> 唔，这边在 Windows 的 Firefox 上面也尝试了一下，也是有同样的问题呢。

但是我看起来没有问题啊……用的是 Firefox 81.0.1 (64 位)。

![out.gif](https://i.loli.net/2020/10/10/QM1ab3di2fTxjUF.gif)

**Comment by FiveYellowMice** [comment]
唔，在尝试自己录像证明自己这边确实不可以的时候，发现自己的错误了！

黄鼠在测试的时候，都是点开自定义颜色选择工具后，没有更改颜色的选择就点击了确定，所以就没有触发 change 事件。而在修改了颜色选择之后，就在 Windows 和 Linux 里面都可以了 `_(:3)<)_` 。之所以在 Chrome 中感觉不到这样的问题，只是因为 Chrome 的选择工具没有确定按钮，所以就下意识地觉得一定要选择一下颜色才可以。

是黄鼠没有仔细尝试就判定问题惹。

不过现在的情况似乎也可以算作另外一个问题的发现：自定义颜色一定要在更改了选择的颜色之后才会被应用，如果想要多次应用同样的自定义颜色，就会需要先把自定义颜色更改成为另外的，然后再更改回来，也是一个用户体验的问题呢。

**Comment by tcdw** [comment]
好吧，现在要考虑的一个问题就是「弹出窗口以后取消选择」和「弹出窗口以后选择了相同的颜色」这两种情况不太好区分……

可能需要完全重新设计这个 UI 的逻辑。

**Comment by tcdw** [comment]
UI 逻辑改掉了，不用原生的调色板组件了。
